### ISSUE TITLE
Filtering for confident events per tissue

### ISSUE THREAD

**Issue by bernardo-de-almeida** [gagneurlab/splicemap#4]
Hi,
I have a question about the SpliceMap tables on Zenodo(https://zenodo.org/record/6408906). I would like to get the splicing events (acceptor and donor) confidently captured in a given tissue. I see that in the tables you also include events supported by few reads and in genes that are not expressed. In your experience, what is a good way of filtering for the confident events?
Maybe I missed this information, but I couldn't find it in the methods.
Thanks!

**Comment by WagnerNils** [comment]
Hi Bernardo,
thank you for your question. In the SpliceMaps we only include junctions that have at least 1 read in 5% of samples. We furthermore report aggregate statistics that you could use for filtering: 
- `k`: the total number of split reads across samples supporting the junction
- `n`: the total number of split reads across samples sharing the same splice site
- `median_n`: the median number of split reads per sample sharing the splice site 

We suggest to use `median_n` for filtering for confidently captured events. See also the [example notebook to generate SpliceMap](https://github.com/gagneurlab/splicemap/blob/master/notebooks/example.ipynb). For the SpliceMaps that we provide in the manuscript we did not apply a `median_n` filter (as different users might be interested in different levels of confidence), but you could apply it already when generating the SpliceMap, with `ct_psi5 = ct.event5_median_filter(cutoff=cutoff)` in the notebook. 
In the context of aberrant splicing prediction, higher cutoffs will likely lead to better precision in the low recall region; however to the expense of lower overall recall.
For AbSplice we used a `median_n` cutoff of 10 reads to filter for expressed splice sites. 
In the SpliceMaps we also provide TPM values for the gene (column `gene_tpm`) that you could use for further filtering.

Let me know if you need additional help.

**Comment by bernardo-de-almeida** [comment]
Thank you very much, Nils! That's exactly the type of information I needed. Congrats on this great work!

**Comment by bernardo-de-almeida** [comment]
Another quick question: what is the difference between the *psi3* and *psi5* files for each tissue?

**Comment by bernardo-de-almeida** [comment]
Hi Nils, another quick question: why do you have a table with psi3 and another with psi5 per tissue? I can see in the example notebook that it is because of different filters at event5 and event3, but how should one combine the tables to get confident annotation of junctions and splicing sites per tissue?
I couldn't get it from the methods. Thanks!

**Comment by WagnerNils** [comment]
Hi Bernardo, psi3 has a fixed acceptor site and alternative donor sites in the splicing event. psi5 has a fixed donor site and alternative acceptor sites. A junction can be part of different splicing events in psi3 and psi5. With the event5 and event3 filter we filter events based on their median_n counts (median number of split reads per sample sharing the same fixed splice site). So it could be that some junctions only appear in psi3 or psi5, depending on the reads of all alternative sites in the event. Furthermore the reference PSI values for psi3 and psi5 can be different for the same junction (as they are different splicing events). 

If you want to combine the tables you can filter them with the strategies discussed above. Then you can combine them and call a junction confidently annotated if it appears in both psi3 and psi5.

**Comment by bernardo-de-almeida** [comment]
Got it, makes sense. Thanks!

**Comment by algaebrown** [comment]
Oh I don't think this is right. The sum of k per splice site is always N

> Hi Bernardo,
> 
> I wonder to get aggregated statistics for each acceptor, is it to read psi3.csv, groupby splice site, aggregate k and N, then divide aggregated k by aggregated N? Trying to make sure I understand the paper correctly. Thanks.

**Comment by WagnerNils** [comment]
Hi algaebrown,
the SpliceMaps already contain aggregated statistics. As mentioned above (first response) these are k, n and median_n. 
- `k`: the total number of split reads across samples supporting the junction
- `n`: the total number of split reads across samples sharing the same splice site
- `median_n`: the median number of split reads per sample sharing the splice site 

You are right, that n is always the sum of k per splice site. From k and n we then compute PSI values (reference PSI, column called `ref_psi`) for each junction in the splicing event. Let me know if you need any further clarification on these definitions or if I can help you with something related to the SpliceMaps.
